[package]
name = "chat-p2p"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.37", features = ["full"] }
tokio-tungstenite = "0.21"
tungstenite = "0.21"
futures-util = "0.3"
url = "2.5"
dirs = "5.0"
base64 = "0.21"
uuid = { version = "1.8", features = ["v4"] }

